Repository ratatui/ratatui, pull requests merged in 2023-04, with the labels that each got.

#129 fix(examples): update input in examples to only use press events
  examples/demo/crossterm.rs
  examples/list.rs
  examples/popup.rs
  examples/table.rs
  examples/tabs.rs
Labels: bug

#36 feat(block): support placing the title on bottom
  src/widgets/block.rs
  tests/widgets_block.rs
Labels: enhancement

#152 refactor(examples): refactor paragraph example
  examples/paragraph.rs
Labels: enhancement

#20 feat(widget): support adding padding to Block
  examples/block.rs
  src/widgets/block.rs
  src/widgets/mod.rs
  tests/widgets_paragraph.rs
Labels: enhancement

#154 docs(readme): add acknowledgement section
  README.md
Labels: documentation
