Repository ratatui/ratatui, pull requests merged in 2023-03, with the labels that each got.

#79 chore(ci): Change the target branch to main
  .github/workflows/ci.yml
Labels: CI

#80 fix(ci): Bump Rust version to 1.63.0
  .github/workflows/ci.yml
Labels: CI

#31 Fix: cassowary/layouts: add extra constraints for fixing Min(v)/Max(v) combination.
  src/layout.rs
Labels: bug

#99 docs(apps): move 'apps using ratatui' to dedicated file (#98)
  APPS.md
  README.md
Labels: documentation

#100 docs(readme): add install instruction and update title
  README.md
Labels: documentation

#35 docs(canvas): add documentation for x_bounds, y_bounds
  src/widgets/canvas/mod.rs
Labels: documentation

#101 docs(readme): small edits before first release
  README.md
Labels: documentation

#112 docs(changelog): update the empty profile link in contributors
  CHANGELOG.md
Labels: documentation

#115 refactor(style): Mark some Style fns const so they can be defined globally
  src/style.rs
Labels: enhancement

#26 refactor(example): remove redundant `vec![]` in `user_input` example
  examples/user_input.rs
Labels: documentation
