Repository ratatui/ratatui, pull requests merged in 2023-02, with the labels that each got.

#46 doc: Updated readme and contributing guide with updates about the fork
  CONTRIBUTING.md
  README.md
Labels: documentation

#48 Update README.md
  README.md
Labels: documentation

#40 Add link to EDMA app in application list
  README.md
Labels: documentation

#39 docs: Add ruscode to list of apps using tui-rs
  README.md
Labels: documentation

#37 docs: add tui-input and update xplr in README.md
  README.md
Labels: documentation

#21 docs: Expand "Apps" and "Third-party" sections
  README.md
Labels: documentation

#30 fix: Ignore zero-width symbol on rendering `Paragraph`
  src/widgets/paragraph.rs
Labels: bug

#44 Update example: Read input only when key was pressed
  examples/user_input.rs
Labels: documentation

#17 feat(widget): add `width()` to ListItem
  src/widgets/list.rs
Labels: enhancement

#10 feat(widget): add `offset()` to `TableState`
  src/widgets/table.rs
Labels: enhancement

#67 docs(contributing): specify the use of unsafe for optimization
  CONTRIBUTING.md
Labels: documentation

#68 docs(github): remove pull request template
  .github/pull_request_template.md
Labels: documentation

#73 docs(readme): Add app kubectl-watch which uses tui
  README.md
Labels: documentation

#74 docs(readme): Add oxker to application list
  README.md
Labels: documentation

#42 fix(widget)!: List should not ignore empty string items
  src/text.rs
  tests/widgets_list.rs
Labels: bug

#76 fix(ci): use env for the cargo-make version
  .github/workflows/ci.yml
Labels: CI

#77 chore: Integrate `committed` for checking conventional commits
  .github/workflows/ci.yml
  committed.toml
Labels: CI
