Repository ratatui/ratatui, pull requests merged in 2023-06, with the labels that each got.

#204 docs: update README.md and add hello_world example
  Cargo.toml
  README.md
  examples/hello_world.rs
Labels: documentation

#205 build(deps)!: upgrade bitflags to 2.3
  Cargo.toml
  src/buffer.rs
  src/style.rs
  src/widgets/mod.rs
Labels: breaking change

#191 chore: lint and doc cleanup
  Cargo.toml
  src/backend/mod.rs
  src/buffer.rs
  src/layout.rs
  src/terminal.rs
  src/widgets/reflow.rs
Labels: documentation

#222 chore(commitizen): add commitizen config
  .cz.toml
  CONTRIBUTING.md
Labels: enhancement

#272 docs: fix scrollbar ascii illustrations and calendar doc paths
  src/widgets/block.rs
  src/widgets/calendar.rs
  src/widgets/scrollbar.rs
Labels: documentation
