Repository ratatui/ratatui, pull requests merged in 2024-07, with the labels that each got.

#1205 feat(chart): add GraphType::Bar
  examples/chart.rs
  src/widgets/chart.rs
Labels: Effort: Easy, Status: Review Needed

#1226 fix(buffer): dont render control characters
  src/buffer/buffer.rs
Labels: Status: Accepted

#1204 refactor(list): split up list.rs into smaller modules
  Cargo.toml
  src/buffer.rs
  src/layout.rs
  src/terminal.rs
  src/text.rs
  src/widgets/list.rs
  src/widgets/list/item.rs
  src/widgets/list/list.rs
  src/widgets/list/rendering.rs
  src/widgets/list/state.rs
  src/widgets/table.rs
Labels: Effort: Easy, Status: Review Needed

#1202 docs(paragraph): update main docs
  src/widgets/paragraph.rs
Labels: Type: Documentation, Effort: Easy, Status: Review Needed

#1190 docs(block): add docs about style inheritance
  src/widgets/block.rs
Labels: Status: Review Needed

#1234 feat(text)!: remove unnecessary lifetime from ToText trait
  src/text/text.rs
Labels: breaking change

#1238 fix: clippy lints from rust 1.80.0
  src/text.rs
  src/widgets/block.rs
  src/widgets/list/list.rs
  src/widgets/table/table.rs
Labels: Effort: Easy, Priority: High

#1214 chore(changelog): fixup git-cliff formatting
  cliff.toml
Labels: Type: Documentation, Status: Do Not Merge, Status: Pending
